version: '3.8'

services:
  dashboard-app:
    build: .
    restart: always
    environment:
      - HOSTNAME=0.0.0.0 
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "3001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/dashboard.crt:/etc/nginx/ssl/dashboard.crt
      - ./nginx/dashboard.key:/etc/nginx/ssl/dashboard.key
    depends_on:
      - dashboard-app