version: '3.8'

services:
  # Database Baru: PostgreSQL
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password_rahasia}
      POSTGRES_DB: ${POSTGRES_DB:-bi_system_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Port ini opsional dibuka jika ingin remote dari laptop (DBeaver/Navicat)
    ports:
      - "5432:5432"

  dashboard-app:
    build: .
    restart: always
    environment:
      - PORT=3001
      - HOSTNAME=0.0.0.0 
      # URL Database untuk Prisma (Penting: pakai nama service 'db' sebagai host)
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      # ClickHouse tetap seperti sebelumnya
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "3001:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/dashboard.crt:/etc/nginx/ssl/dashboard.crt
      - ./nginx/dashboard.key:/etc/nginx/ssl/dashboard.key
    depends_on:
      - dashboard-app

volumes:
  postgres_data: