apiVersion: v1
kind: Service
metadata:
  name: dashboard-bsp-service
  namespace: default
spec:
  selector:
    # Harus sama persis dengan label pada Pod dashboard-bsp Anda
    app: dashboard-bsp
  ports:
    - protocol: TCP
      port: 80         # Port yang diakses di dalam cluster
      targetPort: 3000 # Port aplikasi di dalam container (sesuaikan jika bukan 3000)
      nodePort: 30080  # Port yang dibuka di IP Server (Range: 30000-32767)
  type: NodePort